### ISSUE TITLE
levain path DESTROYS user PATH

### ISSUE THREAD

**Issue by jmoalves** [jmoalves/levain#1]
The user defined PATH is erased when levain is installed.

This is the result of
```batch
setx PATH ...
```

**Comment by rafawalter** [comment]
https://stackoverflow.com/questions/19287379/how-do-i-add-to-the-windows-path-variable-using-setx-having-weird-problems

**Comment by jmoalves** [comment]
The proposed solution worked. I've created the userPath.cmd for this task.
We should add a 'setUserPath' action or something like that later.
