### ISSUE TITLE
Suggest similar recipes when passed as parameter had a typo

### ISSUE THREAD

**Issue by rafawalter** [jmoalves/levain#100]
Similiar to what git does on `git cone` instead of `git clone`

```
~ % git cone
git: 'cone' is not a git command. See 'git --help'.

The most similar command is
	clone
```

**Comment by jmoalves** [comment]
Some lib options to implement this:
* https://github.com/jfmdev/simple-spellchecker
* https://github.com/gustf/js-levenshtein

* https://github.com/asterics/predictionary

**Comment by jmoalves** [comment]
We have issues using js libraries. Here are some options (but they didn't work):
* import * as SpellChecker from "https://unpkg.com/simple-spellchecker";
* import * as SpellChecker from "https://jspm.dev/simple-spellchecker";
