### ISSUE TITLE
Cliffy prompt throwing "os error 6" at Windows 7

### ISSUE THREAD

**Issue by jmoalves** [jmoalves/levain#152]
Running at Windows 7, the Cliffy prompt throws an "os error 6".

Perhaps the following issues may help:
* https://github.com/denoland/deno/issues/5943
* https://github.com/denoland/deno/issues/16195

Although the Deno issue is closed, this is happening with Deno 1.23.2+

**Comment by rafawalter** [comment]
Cliffy 0.25.2 fixed the error above.

Back to "os error 6" described in this issue on Windows 7, Deno 1.25.2 and Cliffy 0.25.2

Works with Windows 7, Deno 1.23.2, Cliffy 0.25.1

**Comment by jmoalves** [comment]
Abandoning Win 7
